apiVersion: v1
kind: Service
metadata:
  labels:
    app: galaxy-ui
  name: galaxy-ui
  namespace: galaxy
spec:
  type: LoadBalancer
  ports:
  - name: "galaxy-ui-service"
    port: 80
    targetPort: 80
  selector:
    app: galaxy-ui